"""
Django settings for plateforme_parrainage project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b*!2isvhm#d!^-0x8=d-#g(!0yprh%uutl-6l*5gjz91q_s31q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.118.45","red-pv76.onrender.com", "127.0.0.1", "www.inverted.sbs", "inverted.sbs"]


# Application definition
# Autoriser ton domaine Render pour CSRF
CSRF_TRUSTED_ORIGINS = [
    "https://red-pv76.onrender.com", "https://inverted.sbs"
]
INSTALLED_APPS = [

      #'colorfield',
      #'admin_interface',

    'django.contrib.admin',
    'django.contrib.auth',

    'django.contrib.humanize',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # app creer par joseph
    'applications.comptes',
    'applications.portefeuille',
    'applications.paiements',
    'applications.produits',
    'applications.parrainages',
    'applications.noyau',
    'applications.shop',
    'applications.prets',
    'applications.chat',
    'channels',
   
   




]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'applications.noyau.middleware.AdminAccessMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'plateforme_parrainage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'applications.noyau.context_processors.withdraw_permission',
                 
            ],
        },
    },
]

WSGI_APPLICATION = 'plateforme_parrainage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'genius22$genius_mysql',   # Nom de la base
        'USER': 'genius22',              # Nom d'utilisateur
        'PASSWORD': 'jos123@@',  # remplace par ton vrai mot de passe MySQL
        'HOST': 'genius22.mysql.pythonanywhere-services.com',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}"""



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/



TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Kinshasa'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')




MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'comptes.Utilisateur'

# Channels
ASGI_APPLICATION = 'plateforme_parrainage.asgi.application'

# Environnement de développement : InMemoryChannelLayer
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}


LOGIN_URL = '/connexion/'
LOGIN_REDIRECT_URL = '/tableau_de_bord/'
LOGOUT_REDIRECT_URL = '/connexion/'


HANDLER404 = "noyau.views.custom_404"

# configuration minimale pour les modèles de langage (LLM)
# activez ces variables et fournissez des clés si vous souhaitez
# que le chat réponde automatiquement via OpenAI ou HuggingFace.
ASSISTANT_USE_OPENAI = False
ASSISTANT_OPENAI_MODEL = 'gpt-3.5-turbo'
ASSISTANT_USE_HF = False
HF_INFERENCE_MODEL = 'google/flan-t5-small'
# chemin vers un fichier texte contenant la base de connaissances que l'IA
# pourra inclure automatiquement dans ses prompts si présent.
KNOWLEDGE_BASE_PATH = BASE_DIR / 'knowledge_base.txt'

