# Generated by Django 4.2 on 2025-09-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigurationSysteme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(max_length=64, unique=True, verbose_name="Clé"),
                ),
                ("valeur", models.TextField(verbose_name="Valeur")),
                (
                    "mis_a_jour_le",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
        ),
    ]
