# Generated by Django 4.2 on 2025-09-16 23:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_au_moment_achat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Prix au moment de l'achat",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(auto_now_add=True, verbose_name="Date de début"),
                ),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "jours_payes",
                    models.PositiveIntegerField(default=0, verbose_name="Jours payés"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("expire", "Expiré"),
                            ("annule", "Annulé"),
                        ],
                        default="actif",
                        max_length=12,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "est_reinvesti",
                    models.BooleanField(default=False, verbose_name="Est réinvesti"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=80, verbose_name="Nom du produit")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Prix"
                    ),
                ),
                (
                    "duree_jours",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Durée en jours"
                    ),
                ),
                (
                    "taux_quotidien",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.05"),
                        max_digits=6,
                        verbose_name="Taux quotidien",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Est actif"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="produits/",
                        verbose_name="Image du produit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GainQuotidien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.DateField(verbose_name="Jour")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "poste",
                    models.BooleanField(
                        default=False, verbose_name="Posté au portefeuille"
                    ),
                ),
                (
                    "poste_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de postage"
                    ),
                ),
                (
                    "achat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gains_quotidiens",
                        to="produits.achat",
                        verbose_name="Achat",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="achat",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="produits.produit",
                verbose_name="Produit",
            ),
        ),
        migrations.AddField(
            model_name="achat",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
