# Generated by Django 4.2 on 2025-09-17 09:54

import applications.portefeuille.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portefeuille", "0002_alter_capitalclient_capital_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionportefeuille",
            name="reference",
            field=models.CharField(
                default=applications.portefeuille.models.generate_reference,
                editable=False,
                max_length=64,
                verbose_name="Référence",
            ),
        ),
    ]
