# Generated by Django 4.2 on 2025-11-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0003_alter_transactionportefeuille_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionportefeuille',
            name='type',
            field=models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('gain_quotidien', 'Gain quotidien'), ('bonus_parrainage', 'Bonus parrainage'), ('achat', 'Signer contrat'), ('bonus_inscription', 'Bonus inscription'), ('capital', 'à retirer capital')], max_length=24, verbose_name='Type de transaction'),
        ),
    ]
