# Generated by Django 4.2 on 2025-09-16 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusParrainage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pourcentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("est_premier_achat", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "achat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="produits.achat"
                    ),
                ),
                (
                    "filleul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_parrain",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_parrainages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("parrain", "filleul")},
            },
        ),
    ]
