# Generated by Django 4.2.27 on 2026-02-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_emprunteur',
            field=models.BooleanField(default=False, verbose_name='Est emprunteur'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='limite_emprunt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Limite d'emprunt"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='montant_emprunt_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant emprunt actuel'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='score_credit',
            field=models.IntegerField(default=0, verbose_name='Score de crédit'),
        ),
    ]
