# Generated by Django 4.2.27 on 2026-03-07 10:24

import applications.comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_utilisateur_adresse_utilisateur_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(default=applications.comptes.models.generer_code_parrainage, max_length=20, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
