# Generated by Django 4.2 on 2025-09-16 23:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraisRetrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la tranche de frais"
                    ),
                ),
                (
                    "type_frais",
                    models.CharField(
                        choices=[
                            ("pourcentage", "Pourcentage"),
                            ("fixe", "Frais fixe"),
                            ("mixte", "Mixte (fixe + pourcentage)"),
                        ],
                        default="mixte",
                        max_length=12,
                        verbose_name="Type de frais",
                    ),
                ),
                (
                    "montant_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Montant minimum",
                    ),
                ),
                (
                    "montant_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Laissez vide pour les tranches sans limite supérieure",
                        max_digits=12,
                        null=True,
                        verbose_name="Montant maximum",
                    ),
                ),
                (
                    "frais_fixe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Frais fixe",
                    ),
                ),
                (
                    "frais_pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pourcentage appliqué au montant du retrait",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Frais en pourcentage",
                    ),
                ),
                (
                    "frais_minimum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Frais minimum à appliquer même si le calcul donne moins",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Frais minimum",
                    ),
                ),
                (
                    "frais_maximum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Frais maximum à appliquer même si le calcul donne plus",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Frais maximum",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'application"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Frais de retrait",
                "verbose_name_plural": "Frais de retrait",
                "ordering": ["montant_min"],
            },
        ),
        migrations.CreateModel(
            name="Retrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "methode",
                    models.CharField(max_length=32, verbose_name="Méthode de retrait"),
                ),
                (
                    "destination",
                    models.CharField(
                        max_length=128,
                        verbose_name="Destination (numéro de compte/téléphone)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demande", "Demandé"),
                            ("en_traitement", "En traitement"),
                            ("paye", "Payé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="demande",
                        max_length=13,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "traite_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de traitement"
                    ),
                ),
                (
                    "frais",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Frais de retrait",
                    ),
                ),
                (
                    "montant_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Montant net",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retraits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Depot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                ("methode", models.CharField(max_length=32)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirme", "Confirmé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="confirme",
                        max_length=12,
                    ),
                ),
                (
                    "reference",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("confirme_le", models.DateTimeField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
