# Generated by Django 4.2.27 on 2026-03-03 18:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraitCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_approuve', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('reject', 'Rejeté'), ('en_remboursement', 'En remboursement'), ('rembourse', 'Remboursé')], default='demande', max_length=20)),
                ('nombre_filleuls_requis', models.PositiveIntegerField(default=5)),
                ('nombre_filleuls_valides', models.PositiveIntegerField(default=0)),
                ('est_eligible', models.BooleanField(default=False)),
                ('pourcentage_remboursement', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Pourcentage des gains quotidiens à prélever pour le remboursement', max_digits=5)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('demande_le', models.DateTimeField(auto_now_add=True)),
                ('approuve_le', models.DateTimeField(blank=True, null=True)),
                ('debute_le', models.DateTimeField(blank=True, null=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('raison_rejet', models.TextField(blank=True, null=True)),
                ('pret', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrait_credit', to='prets.pret')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits_credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retrait Crédit',
                'verbose_name_plural': 'Retraits Crédits',
                'unique_together': {('utilisateur', 'pret')},
            },
        ),
        migrations.CreateModel(
            name='EligibiliteRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_max_autorise', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('nombre_filleuls_requis', models.PositiveIntegerField(default=5)),
                ('nombre_filleuls_valides', models.PositiveIntegerField(default=0, help_text='Nombre de filleuls avec achats validés')),
                ('est_eligible', models.BooleanField(default=False)),
                ('derniere_verification', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilite_retrait', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eligibilité Retrait',
                'verbose_name_plural': 'Eligibilités Retraits',
            },
        ),
        migrations.CreateModel(
            name='AjustementRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_gain', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pourcentage_applique', models.DecimalField(decimal_places=2, max_digits=5)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('applique', 'Appliqué'), ('annule', 'Annulé')], default='en_attente', max_length=15)),
                ('applique_le', models.DateTimeField(blank=True, null=True)),
                ('gain_quotidien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.gainquotidien')),
                ('retrait_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements', to='prets.retraitcredit')),
            ],
            options={
                'verbose_name': 'Ajustement Remboursement',
                'verbose_name_plural': 'Ajustements Remboursements',
            },
        ),
    ]
