# Generated by Django 4.2.27 on 2026-03-05 14:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0002_retraitcredit_eligibiliteretrait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibiliteretrait',
            name='montant_max_autorise',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12),
        ),
    ]
